# Generated by Django 3.0.5 on 2020-10-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
