# Generated by Django 3.0.5 on 2020-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_api', '0002_auto_20201010_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
